### ISSUE TITLE
options.warn is not a function

### ISSUE THREAD

**Issue by MattWilliamsDev** [webpack/webpack-dev-middleware#133]
Recent change to `middleware.js` broke build process.  Process works on `webpack-dev-server@~1.15.0`, but not at `~1.18.0`.  Unsure where it broke in between those two.

This is the error thrown during the gulp start task:
```
TypeError: options.warn is not a function
    at module.exports ([project]/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:42:11)
    at new Server ([project]/node_modules/webpack-dev-server/lib/Server.js:53:20)
    at Gulp.<anonymous> ([project]/gulpfile.babel.js:77:9)
    at module.exports ([project]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask ([project]/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep ([project]/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at [project]/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish ([project]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at [project]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f ([project]/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
```

Here is the code from my gulpfile:
```
gulp.task( 'serve:start', [ 'serve:static' ], () => {
	const config = webpackConfig( true, 'build', PORT );
	return new WebpackDevServer( webpack( config ), {
		contentBase: 'build',
		publicPath: config.output.publicPath,
		watchDelay: 100
	}).listen( PORT, '0.0.0.0', err => {
		if ( err ) throw new $.util.PluginError( 'webpack-dev-server', err );
		$.util.log( `[ ${ packageJson.name } serve ]`, `Listening at localhost:${ PORT }` );
	});
});
```

Let me know if more detail is needed.

**Comment by SpaceK33z** [comment]
This was already fixed in #131. Meanwhile, if you want to fix this, use `watchOptions: { aggregateTimeout: 100 }` instead.

**Comment by MattWilliamsDev** [comment]
Thank you for the reply. I worked around it via `npm shrinkwrap`, but will implement your suggestion as well.
