### PR TITLE
use res.send instead of res.end to enable etag.

### PR DESCRIPTION
**Pull request by kgdev**
use res.send instead of res.end to enable etag.

### CODE REVIEW

**Comment by bebraw** [comment]
:+1:

**Comment by sokra** [comment]
Thanks

**Comment by mgol** [comment]
This breaks using the dev server as a middleware for `browser-sync`:
```js
var config = {/*...*/}
var server = require('browser-sync');
var compiler = webpack(config);

serve({
    port: process.env.PORT || 3000,
    open: false,
    server: {baseDir: 'server/dist/},
    middleware: [
        webpackDevMiddleware(compiler, {
            stats: {
                chunks: false,
                modules: false,
            },
            publicPath: config.output.publicPath,
        }),
    ],
});
```

It worked fine with  `webpack-dev-middleware@1.4.0` but with `1.5.0` I get:
```
TypeError: res.send is not a function
    at processRequest (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/webpack-dev-middleware/middleware.js:189:8)
    at ready (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/webpack-dev-middleware/middleware.js:96:20)
    at webpackDevMiddleware (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/webpack-dev-middleware/middleware.js:162:3)
    at call (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:239:7)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:183:5)
    at respModifierMiddleware (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/resp-modifier/index.js:80:9)
    at call (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:239:7)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:183:5)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:161:14)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:161:14)
    at utils.handleOldIE (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/browser-sync/lib/server/utils.js:95:16)
    at call (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:239:7)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:183:5)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:161:14)
    at Function.handle (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:186:3)
    at Server.app (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:51:37)
TypeError: res.send is not a function
    at processRequest (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/webpack-dev-middleware/middleware.js:189:8)
    at ready (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/webpack-dev-middleware/middleware.js:96:20)
    at webpackDevMiddleware (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/webpack-dev-middleware/middleware.js:162:3)
    at call (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:239:7)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:183:5)
    at respModifierMiddleware (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/resp-modifier/index.js:80:9)
    at call (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:239:7)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:183:5)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:161:14)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:161:14)
    at utils.handleOldIE (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/browser-sync/lib/server/utils.js:95:16)
    at call (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:239:7)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:183:5)
    at next (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:161:14)
    at Function.handle (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:186:3)
    at Server.app (/Users/mgol/Documents/projects/yougov/entities-manager/node_modules/connect/index.js:51:37)
```

**Comment by wgcrouch** [comment]
I get the same error using gulp-connect
